event_target_list = '//input[@name="__EVENTTARGET"]/@value'
event_argument_list = '//input[@name="__EVENTARGUMENT"]/@value'
view_state_list = '//input[@name="__VIEWSTATE"]/@value'
event_validation_list = '//input[@id="__EVENTVALIDATION"]/@value'
view_state_encrypted_list = '//input[@id="__VIEWSTATEENCRYPTED"]/@value'
view_state_result_list = '//input[@id="__VIEWSTATE"]/@value'
view_state_encrypted_result_list = '//input[@id="__VIEWSTATEENCRYPTED"]/@value'
event_validation_result_list = '//input[@id="__EVENTVALIDATION"]/@value'
nodes_list = '//table[contains(@id, "gvSearch")]//tr'
case_url_list = './/td[1]/a/@href'
case_year_list = './/td[2]/text()'
token_no_list = './/td[3]/text()'
petitioner_name_list = './/td[4]/text()'
respondent_name_list = './/td[5]/text()'
filing_date_list = './/td[6]/text()'
pet_advocate_list = './/span[contains(@id, "Label2")]/text()'
token_number_xpath = '//table[@class="CSSCaseStatus"]//th[contains(text(), "Token Number")]/..//following-sibling::td/span[contains(@id, "CaseNo")]/text()'
case_status_xpath = '//table[@class="CSSCaseStatus"]//th[contains(text(), "Status :")]/..//following-sibling::td/span[contains(@id, "Label5")]/text()'
petitioner_xpath = '//table[@class="CSSCaseStatus"]//th[contains(text(), "Petitioner")]/..//following-sibling::td/span[contains(@id, "Label6")]/text()'
respondent_xpath = '//table[@class="CSSCaseStatus"]//th[contains(text(), "Respondent")]/..//following-sibling::td/span[contains(@id, "Label3")]/text()'
date_filing_xpath = '//table[@class="CSSCaseStatus"]//th[contains(text(), "Date of Filing")]/..//following-sibling::td/span[contains(@id, "Label1")]/text()'
case_no_xpath = '//table[@class="CSSCaseStatus"]//th[contains(text(), "Case No.")]/..//following-sibling::td//a[contains(@id, "HyperLink")]/text()'
