family_name_xpath = '//tr//td[contains(text(), "Present family name:")]/following-sibling::td/text()'
fore_name_xpath = '//tr//td[contains(text(), "Forename:")]/following-sibling::td/text()'
sex_xpath = '//tr//td[contains(text(), "Sex:")]/following-sibling::td/text()'
date_of_birth_xpath = '//tr//td[contains(text(), "Date of birth:")]/following-sibling::td/text()'
place_of_birth_xpath = '//tr//td[contains(text(), "Place of birth:")]/following-sibling::td/text()'
language_spoken_xpath = '//tr//td[contains(text(), "Language spoken:")]/following-sibling::td/text()'
nationality_xpath = '//tr//td[contains(text(), "Nationality:")]/following-sibling::td/text()'
charges_xpath = '//p[@class="charge"]//text()'
regions_where_wanted_xpath = '//div//span[@class="nom_fugitif_wanted_small"]//text()'
